# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEV',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('48b90fa8-a868-11e8-a8d1-c4b3018f55c6'), editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7ec8\u7aef\u540d\u79f0')),
                ('eth1', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7f51\u53611')),
                ('eth2', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7f51\u53612')),
                ('mac', models.CharField(blank=True, max_length=20, null=True, verbose_name='MAC')),
                ('system_version', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u7248\u672c\u53f7')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('guarantee_date', models.DateField(blank=True, null=True, verbose_name='\u4fdd\u4fee\u65f6\u95f4')),
                ('dev_cabinet_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8bbe\u5907\u4f4d\u7f6e')),
                ('number', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('editor', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('status', models.IntegerField(blank=True, choices=[(0, '\u672a\u6fc0\u6d3b'), (1, '\u79bb\u7ebf'), (2, '\u5728\u7ebf')], default=0, verbose_name='\u673a\u5668\u72b6\u6001')),
                ('type', models.IntegerField(blank=True, default=1, verbose_name='\u4e3b\u673a\u7c7b\u578b')),
                ('server_sn', models.CharField(blank=True, max_length=32, null=True, verbose_name='SN\u7f16\u53f7')),
                ('switch_port', models.CharField(blank=True, max_length=12, null=True, verbose_name='\u7aef\u53e3\u53f7')),
                ('idle', models.BooleanField(choices=[(True, '\u4f7f\u7528\u4e2d'), (False, '\u7a7a\u95f2')], default=1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907',
                'verbose_name_plural': '\u8bbe\u5907',
            },
        ),
    ]
