# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d740b45e-a868-11e8-9e5d-c4b3018f55c6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
