# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180825_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2a63fe0c-a869-11e8-b6d6-c4b3018f55c6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
