# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20180825_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='storeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.STORE', verbose_name='\u6240\u5c5e\u95e8\u5e97'),
        ),
        migrations.AlterField(
            model_name='dev',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d8feb999-a869-11e8-9670-c4b3018f55c6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, '\u52a0\u76df'), (1, '\u76f4\u8425')], null=True, verbose_name='\u95e8\u5e97\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='store',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d8fd46c7-a869-11e8-a3a6-c4b3018f55c6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
